# Nord color palette definitions
nord0: &nord0 "#2e3440"
nord1: &nord1 "#3b4252"
nord2: &nord2 "#434c5e"
nord3: &nord3 "#4c566a"
nord4: &nord4 "#d8dee9"
nord5: &nord5 "#e5e9f0"
nord6: &nord6 "#eceff4"
nord7: &nord7 "#8fbcbb"
nord8: &nord8 "#88c0d0"
nord9: &nord9 "#81a1c1"
nord10: &nord10 "#5e81ac"
nord11: &nord11 "#bf616a"
nord12: &nord12 "#d08770"
nord13: &nord13 "#ebcb8b"
nord14: &nord14 "#a3be8c"
nord15: &nord15 "#b48ead"

general:
  focus_follows_cursor: true
  cursor_follows_focus: false
  toggle_workspace_on_refocus: true
  show_floating_on_top: false
  floating_window_move_amount: "5%"
  center_new_floating_windows: true
  window_animations: "unchanged"

gaps:
  inner_gap: "2"
  outer_gap: "1"

focus_borders:
  active:
    enabled: true
    color: *nord8
  inactive:
    enabled: false
    color: *nord3

bar:
  height: "28px"
  position: "top"
  opacity: 1.0
  background: *nord1
  foreground: *nord4
  font_family: "JetBrainsMono Nerd Font"
  font_size: "16px"
  padding: "4px 6px"
  offset_x: "0"
  offset_y: "0"
  border_radius: "0"
  component_separator:
    label: "  "
  components_left:
    - type: "workspaces"
      focused_workspace_background: *nord10
      focused_workspace_foreground: *nord0
      displayed_workspace_background: *nord2
      default_workspace_background: "transparent"
  components_center:
    - type: "window title"
  components_right:
    - type: "system tray"
    - type: "clock"
      time_formatting: "dd/MM/yyyy HH:mm"

workspaces:
  - name: "1"
    display_name: "󰋞 1.home"
    # keep_alive: true
  - name: "2"
    display_name: " 2.web"
  - name: "3"
    display_name: " 3.dev"
  - name: "4"
    display_name: " 4.msg"
  - name: "5"
    display_name: " 5.cfg"
  - name: "6"
    display_name: " 6.rdp"
  - name: "7"
    display_name: " 7.games"

window_rules:
  - command: "ignore"
    match_process_name: "/Taskmgr|ScreenClippingHost/"
  - command: "set floating"
    match_class_name: "#32770"
  - command: "ignore"
    match_title: "[Pp]icture.in.[Pp]icture"
    match_class_name: "Chrome_WidgetWin_1|MozillaDialogClass"
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"
  - command: "ignore"
    match_process_name: "eso64|DaggerfallUnity|valheim|OpenMW|openmw|openmw.exe"
  - command: "move to workspace 2"
    match_process_name: "firefox|thorium|chrome"

binding_modes:
  - name: "resize"
    keybindings:
      - command: "resize width -2%"
        bindings: ["H", "Left"]
      - command: "resize width +2%"
        bindings: ["L", "Right"]
      - command: "resize height +2%"
        bindings: ["K", "Up"]
      - command: "resize height -2%"
        bindings: ["J", "Down"]
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  - command: "exec 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'"
    bindings: ["Alt+B"]
  - command: "exec wt"
    bindings: ["Alt+X"]
  - command: "exec explorer"
    bindings: ["Alt+E"]
  - command: "exec '%LOCALAPPDATA%\\Programs\\cursor\\Cursor.exe'"
    bindings: ["Alt+W"]
  - command: "focus left"
    bindings: ["Alt+H", "Alt+Left"]
  - command: "focus right"
    bindings: ["Alt+L", "Alt+Right"]
  - command: "focus up"
    bindings: ["Alt+K", "Alt+Up"]
  - command: "focus down"
    bindings: ["Alt+J", "Alt+Down"]
  - command: "move left"
    bindings: ["Alt+Shift+H", "Alt+Shift+Left"]
  - command: "move right"
    bindings: ["Alt+Shift+L", "Alt+Shift+Right"]
  - command: "move up"
    bindings: ["Alt+Shift+K", "Alt+Shift+Up"]
  - command: "move down"
    bindings: ["Alt+Shift+J", "Alt+Shift+Down"]
  - command: "resize width -2%"
    binding: "Alt+U"
  - command: "resize width +2%"
    binding: "Alt+P"
  - command: "resize height +2%"
    binding: "Alt+O"
  - command: "resize height -2%"
    binding: "Alt+I"
  - command: "binding mode resize"
    binding: "Alt+R"
  - command: "focus mode toggle"
    binding: "Alt+Space"
  - command: "toggle floating"
    binding: "Alt+Shift+Space"
  - command: "toggle maximized"
    binding: "Alt+X"
  - command: "set minimized"
    binding: "Alt+M"
  - command: "close"
    binding: "Alt+Q"
  - command: "exit wm"
    binding: "Alt+Shift+E"
  - command: "reload config"
    binding: "Alt+Shift+R"
  - command: "exec cmd"
    binding: "Alt+Enter"
  - command: "focus workspace recent"
    binding: "Alt+Y"
  - command: "focus workspace next"
    binding: "Alt+T"
  - command: "focus workspace prev"
    binding: "Alt+Shift+T"
  - command: "focus workspace 1"
    binding: "Alt+1"
  - command: "focus workspace 2"
    binding: "Alt+2"
  - command: "focus workspace 3"
    binding: "Alt+3"
  - command: "focus workspace 4"
    binding: "Alt+4"
  - command: "focus workspace 5"
    binding: "Alt+5"
  - command: "focus workspace 6"
    binding: "Alt+6"
  - command: "focus workspace 7"
    binding: "Alt+7"
  - command: "move workspace left"
    binding: "Alt+A"
  - command: "move workspace right"
    binding: "Alt+F"
  - command: "move workspace up"
    binding: "Alt+D"
  - command: "move workspace down"
    binding: "Alt+S"
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Alt+Shift+7"
